[package]
name = "advent-of-code-helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15"
anyhow = "1.0"
clap = { version = "3.0.0-rc.9", features = ["derive"] }
itertools = "0.10"
regex = "1.5"
